[workspace]
members = [
  "bevy_matchbox",
  "matchbox_protocol",
  "matchbox_socket",
  "matchbox_server",
  "matchbox_signaling",
  "examples/*",
]
resolver = "2" # Important! Bevy/WGPU needs this!
